### PR TITLE
New event bus

### PR DESCRIPTION
**Pull request by shadowfacts**
- Merge the event busses into 1 bus
- More consistent OML start/end comments in patches
- Clean up the test mod

### CODE REVIEW

**Comment by Victorious3** [comment]
This requires a lot of registrations, see if there's a way to make it less? Forge's solution isn't the worst when it comes to this, best would be if you didn't need to register anything at all and just stick annotations on methods... This looks really painful to use, I liked the old one better.

**Comment by darkhax** [comment]
@Victorious3 I am pushing for a lazy registry solution for this. Had one in a previous version but everyone disliked it.

**Comment by rubensworks** [comment]
@Victorious3 I actually like this new way better, it gives a lot more flexibility.
An additional wrapper around this could however be added that adds support for annotation-based event-handling.

**Comment by Victorious3** [comment]
@rubensworks I'm not quite sure what you mean by that because the old thing could be used in the exact same way but didn't require a .class parameter and was a lot shorter.

@darkhax Show me?

**Comment by shadowfacts** [comment]
I could add an annotation and a register method that takes an object and registers all the methods in it with annotations and a valid signature.

**Comment by darkhax** [comment]
@Victorious3 It was similar to how Forge does stuff, but it was based on reflection. The reflection part is why people disliked it.

@shadowfacts I would personally prefer the ability to have all events with the defined annotation be registered automatically. The direct system allows for more flexibility in some ways, but also makes things slightly more complicated.

**Comment by Victorious3** [comment]
@darkhax Reflection be replaced by ASM, makes it fast.

**Comment by iLexiconn** [comment]
I think it's fine right now and it doesn't need any further changes. Please stop changing stuff D:

**Pull request merged**
