### PR TITLE
Rewrite FuelRegistry.

### PR DESCRIPTION
**Pull request by MrIbby**
This is the fuel registry equivalent of my rewrite for dictionaries (#67). Burn time getters are the equivalent of Forge's fuel handlers.

Passing the stack to mods allows for more customizability.

There are helper methods for:
* Item stack matchers (`Predicate<ItemStack>`)
* `ItemStack`s with NBT
* `ItemStack`s
* `Item`s
* `Block`s
* Dictionary materials (`String`)
* Block materials (`Material`)
* `Item.ToolMaterial` (`Item.a`)

### CODE REVIEW

**Comment by darkhax** [comment]
The idea of a Fuel Getter is very similar to an event, so why not use those instead and avoid writing a separate system to handle them?

**Comment by MrIbby** [comment]
The problem is, how would you register a fuel?

**Comment by Strikingwolf** [comment]
You could have a fuel registry and the handler chooses the max between the event and the registry. That's essentially what you're doing here

As a one-job Fuel Getter is created to add a fuel to the registry and then you choose max between all Fuel Getters. You could in practice skip a step

Although personally I do like lambdas, and I'm not sure if your event system handles callbacks (if it does then god bless OML)

**Comment by coolsquid** [comment]
Why _would_ you need to register a fuel? It is fully possible to use an event.
    public static int getItemBurnTime(ItemStack var0) {
        if(true) return xyz.openmodloader.event.impl.FuelEvent.handle(var0);
    }

**Comment by MrIbby** [comment]
Yes, it is possible to use an event, but an event is not as simple to use. A fuel registry allows you to register fuels without the need to make your own fuel registry or fuel handler or fuel event handler.

If we used events, I would just make my own registry so I don't have to do this:
``` java
if (item == MyItems.MY_COAL) {
    return 1600;
} else if (item == MyItems.MY_LAVA_BUCKET) {
    return 20000;
}
```

**Comment by coolsquid** [comment]
Then what about we create a FuelRegistry class with default methods that create an event handler for you?

**Comment by MrIbby** [comment]
The FuelRegistry in this PR already has default methods that handle fuels for you.

**Comment by MrIbby** [comment]
Keep in mind, this is a _rewrite_ of `FuelRegistry`. I did not make the original...

**Comment by MrIbby** [comment]
* `FuelEvent`: does not allow global registration.
* @Caellian's `FuelRegistry`: limited to items, block materials, and tool materials.

**Comment by MrIbby** [comment]
Wrong button

**Comment by coolsquid** [comment]
The issue with this FuelRegistry (and the old one) is that it defines a completely unnecessary registry. If we use events, mods can customize it as they want to, and we can still have simple methods in `GameRegistry` for those who prefer that.
> Keep in mind, this is a _rewrite_ of `FuelRegistry`. I did not make the original...

I know, but this is a good chance to take the discussion we should've taken before the previous PR was merged.

**Comment by phase** [comment]
Handling fuels should go on behind the scenes. I don't want to have to handle my fuel in an event listener. Some type of FuelRegistry should be used, but I don't know if it warrants a new class.

**Comment by Victorious3** [comment]
If you want to make it a callback, just add some method to Item, that makes more sense than having to write an if chain and event handler

**Pull request closed without merging**
