### PR TITLE
[WIP] Add PlayerEvent.Brew

### PR DESCRIPTION
**Pull request by MrIbby**
`PlayerEvent.Brew` is fired when a potion (excluding a water bottle) is picked up from a brewing stand.

__NOTE:__ This is _not_ the same as Forge's `PotionBrewEvent`.

### CODE REVIEW

**Comment by darkhax** [comment]
If the event is not fired when a potion is brewed, you should try to find a better name. Like Obtained or Removed

**Comment by MrIbby** [comment]
Why? It's in `PlayerEvent`, which also has the `Craft` and `Smelt` events.

**Comment by Strikingwolf** [comment]
Good PR, though I would ask to stay away from player events as I'm working on those. As well as the fact that I won't be putting all the events in `PlayerEvent` due to there being many of them and I don't want `PlayerEvent` to become an absolutely huge class

**Comment by darkhax** [comment]
The Craft event and Smelt event are actually related to crafting and smelting though. Your event is not fired when a potion is brewed, so the name `Brew` does not accurately describe the event, and would have name conflicts when an actual brew event is implemented. It may actually be better for this to be turned into a generic slot event that is fired whenever any item is removed from a slot.

**Comment by Strikingwolf** [comment]
In that case Craft and Smelt events would have to extend Slot, as would the Repair event that I have constructed in my personal fork

I could reimplement this quickly in terms of SlotEvents in my personal fork (and make a PR for when I actually get enough done on player events) if you wish @darkhax and @MrIbby

**Comment by MrIbby** [comment]
@darkhax `Craft` and `Smelt` are no different from `Brew`... `Craft` is fired when a player picks up an item from a __crafting output__. `Smelt` is fired when a player picks up an item from a __furnace output__. `Brew` is fired when a player picks up an item from a __brewing stand output__.

**Pull request closed without merging**
