### PR TITLE
Add a mod list Gui and Author Compat

### PR DESCRIPTION
**Pull request by TheCodedOne**

### CODE REVIEW

**Comment by TheCodedOne** [comment]
screenshot_3

**Comment by shadowfacts** [comment]
Why are you adding a button that doesn't do anything? IMO y should leave it as a plain string or have the button do something (e.g. Go to a screen with more info).

**Comment by TheCodedOne** [comment]
I will probably work on making it go to a screen with more information, I only didn't since there isn't currently any information for mods

**Comment by iLexiconn** [comment]
Will merge if you make the GUI actually useful :p

**Comment by iLexiconn** [comment]
(icon, version, description, etc)

**Comment by TheCodedOne** [comment]
screenshot_6
screenshot_7

**Comment by iLexiconn** [comment]
I think you should take another look at designing this one. It doesn't looks the best and the text is hard to read.

**Comment by Victorious3** [comment]
Get inspired by Minecraft's world list, all the information you are displaying here can be fitted inside one GUI without a hassle.

**Comment by darkhax** [comment]
Basing the GUI off of the world selection would be really neat. Made a mockup design in Paint ;p
image

**Comment by Victorious3** [comment]
@darkhax Thumbs up for the search bar, great idea!

**Comment by rubensworks** [comment]
@darkhax I like the idea, but I think it might be better if the mods are displayed more compactly. Then it becomes easier to scroll through the mods for larger modpacks.
(Maybe even have the option to switch between normal and compact mode?)

**Comment by darkhax** [comment]
@rubenworks Perhaps it could be similar to the YouTube subscriptions list where you can switch between tiles mode and list mode.

**Comment by TheCodedOne** [comment]
I will rewrite it today at some point, probably based off what darkhax posted but add a compact mode too.

**Comment by modmuss50** [comment]
Yeah, my idea was something like the world selection.

**Comment by TheCodedOne** [comment]
I'll work on doing something like world selection then add a compact mode if deemed necessary.

**Comment by TheCodedOne** [comment]
@darkhax you had description on your image, how would you say to implement that, a new Gui with more info on?

**Comment by darkhax** [comment]
@TheCodedOne Yeah, a new screen that displays all of the info would be preferred.

**Comment by iLexiconn** [comment]
You just screwed the pr up... Make a new one please. (you pulled all the changes we made after you made the pr into it)

**Pull request closed without merging**
