### PR TITLE
Add GuiEvent.KeyPress

### PR DESCRIPTION
**Pull request by shadowfacts**
Allows for intercepting, acting upon, and canceling key presses in GUIs.

### CODE REVIEW

**Comment by iLexiconn** [comment]
I already had an event like this planned. Could you make it not GUI dependent and make it active for every key input in the game?

**Comment by iLexiconn** [comment]
And while you're at it, you might also want to add a mouse input event :P

**Comment by darkhax** [comment]
I am currently refactoring the event system, so this will cause merge conflicts with my local branch. I will reference this PR when it's safe to continue.

**Comment by shadowfacts** [comment]
@iLexiconn Yes, I can change the event so it's fires for every key press. I'm going to do the mouse event as a separate PR to keep things cleaner on my end.

@darkhax Alrighty, I'll put this on hold until then.

**Comment by shadowfacts** [comment]
This PR is being redone to be GUI independent.

**Pull request closed without merging**
